testMode: false
site: "https://www.pinnacle.com/en/esports/matchups/highlights/"
cookieDir: "/home/pararti/gog"
login: "wolfram1602@gmail.com"
password: "choCobo963"
kafkaAddress: "kafka"
kafkaPort: "29092"
kafkaTopic: "bookmaker_event"
logPath: "/var/log/pinacle-parser.log"
userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
dbConnection: "postgresql://postgres:your-super-secret-and-long-postgres-password@postgres:5432/postgres"
producerSentry: "http://5f94f98f2ccd4066a9b03ea9ed30b65d@sentry.wolframko.ru/1"
consumerSentry: "http://c245cbde00eb446abb935bd04e6b021b@sentry.wolframko.ru/2"
remoteChromeURL: "ws://150.241.108.152:3121?token=phkaqmcwvpepqhdc"