testMode: false
site: "https://www.pinnacle.com/en/esports/matchups/highlights/"
cookieDir: "/home/pararti/gog"
login: "wolfram1602@gmail.com"
password: "choCobo963"
kafkaAddress: "localhost"
kafkaPort: "9092"
logPath: "/var/log/pinacle-parser.log"
userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"